repos:
  - id: terraform_fmt
    args:
      - --args=-no-color
      - --args=-diff
      - --args=-write=false
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.33.0
    hooks:
      - id: yamllint
        args: ['-s']
  - repo: local
    hooks:
      - id: trivy
        name: trivy misconfig scan
        entry: trivy
        language: system
        pass_filenames: false
        args:
          - -c
          - .trivy.yaml
          - fs
          - .
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: v0.18.0
    hooks:
      - id: terraform-docs-system
        args:
          - -c
          - .terraform-docs.yml
          - .
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.90.0
    hooks:
      - id: terraform_tflint
