repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.90.0
    hooks:
      - id: terraform_fmt
        files: ^(projects/data-transformation-dbt|projects/iac-shared)/.*  # Run only in dir1 and dir2
      - id: terraform_tflint
      - id: terraform_validate
      # - id: terraform_trivy

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.33.0
    hooks:
      - id: yamllint
        args: ['-s']

  - repo: local
    hooks:
      - id: trivy
        name: trivy misconfig scan
        entry: trivy
        language: system
        pass_filenames: false
        args:
          - -c
          - .trivy.yaml
          - fs
          - .

  - repo: https://github.com/terraform-docs/terraform-docs
    rev: v0.18.0
    hooks:
      - id: terraform-docs-system
        args:
          - -c
          - .terraform-docs.yml
        files: ^(projects/data-transformation-dbt|projects/iac-shared)/.*  # Run only in dir1 and dir2
