dbt_example_dataset:
  dataset:
    dataset_id: dbt_example_dataset
    location: EU
  tables:
    jaffle_shop:
      table_id: jaffle_shop
      schema:
        - name: id
          type: STRING
          mode: REQUIRED
        - name: orderid
          type: FLOAT
          mode: NULLABLE
        - name: paymentmethod
          type: FLOAT
          mode: NULLABLE
        - name: status
          type: FLOAT
          mode: NULLABLE
        - name: amount
          type: FLOAT
          mode: NULLABLE
        - name: created
          type: FLOAT
          mode: NULLABLE
    stripe:
      table_id: stripe
      schema:
        - name: id
          type: STRING
          mode: REQUIRED
        - name: orderid
          type: FLOAT
          mode: NULLABLE
        - name: paymentmethod
          type: FLOAT
          mode: NULLABLE
        - name: status
          type: FLOAT
          mode: NULLABLE
        - name: amount
          type: FLOAT
          mode: NULLABLE
        - name: created
          type: FLOAT
          mode: NULLABLE