example_dataset:
  dataset:
    dataset_id: example_dataset
    location: EU
  tables:
    example_table:
      table_id: example_table
      schema:
        - name: id
          type: STRING
          mode: REQUIRED
        - name: value
          type: FLOAT
          mode: NULLABLE